var GAME_LEVELS = [
  ["yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "    yy!!!!yy        yy!!!!yy         yy!!!!yy           yy!!!!yy        yy!!!!yy",
   "       v                 v              v                    v             v    ",
   "                       v                                   v                    ",
   "         v                                v                                  v  ",
   "                                                    o                           ",
   "                                                   xxx                          ",
   "                                                   !!!                          ",
   "             xxx                                   !!!                          ",
   "  xxxx       !!!                             o  xx !!!                          ",
   "  x          !!!                            o      !!!                          ",
   "  x        o !!!                           xxxx    !!!                          ",
   "  x          !!!                           !!!!    !!!                          ",
   "  x       xxx!!!                           !!!!    !!!                          ",
   "  x          !!!         o                 !!!!    !!!                          ",
   "  x o        !!!        xxx       o        !!!!    !!!                          ",
   "  x          !!!        x x        o       !!!!    !!!                          ",
   "  xxxx       !!!        x x        o       !!!!    !!!                          ",
   "  x          !!!        x x                !!!!    !!!                          ",
   "  x          !!!        x x        o       !!!!    !!!                 o        ",
   "  x          !!!   f    x x   f        f   !!!! f  !!!                 o        ",
   "  x       xxx!!!!!!!!!!!x x!!!!!!!   !!!!!!!!!!!!  !!!                xxxx      ",
   "  x          !!!!!!!!!!!x x!!!!!!!   !!!!!!!!!!!!!!!!!         o                ",
   "  x       o  !!!!!!!!!!!x x!!!!!!!   !!!!xxxxxxxxxxxxx        xxxx              ",
   "  x  @     o !!!!!!!!!!!x x!!!!!!!   !!!!x                    x                 ",
   "  xxxxxxxxxxx!!!xxxxxxxxx xxxxx!!!   !!xxx       o     o  xxxxx                 ",
   "             !!!               !!!   !!x                  xx                    ",
   "             !!!               !!!   xxx        xxxxxxx!!!!x                    ",
   "             !!!               !!!    o         x!!!!!!!!!!x                    ",
   "             !!!               !!!        f     x!!!!!!!!!!x                    ",
   "             !!!               !!!xxxxxxx!!!xxppx!!!!!!!!!!!!!                  ",
   "          !!!!!!!!           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!              "],
  ["yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                                                 ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                                                 ",
   "y!!!yyxxxxxxxxxxxxxxxxxxxxxxxxxx!                                           o                                     ",
   "  v   x                        x!                  o    o               xxx                                       ",
   "      x o o                o o x!                  x    x               !!x                                       ",
   "      x =                      x!          xxx                xxx       !!x                                       ",
   "      x                      = x!            x   f    f    f  x      !!!!!x o                                     ",
   "      x o o                o o x!            xx!!!!!!!!!!!!!!!x      !xxx!x                                       ",
   "      x                        x!!            x!!!!!!!!!!!!!!xx      !x  !                                        ",
   "      xxxxxx   xxxxxxxxxxxxx   x!!!!!!!       x!!!!!!!!!!!!!!x       !x  !        o                               ",
   "           x   x           x   xxxxxxx!       x!!!xxxxxxx!xxxx       !x  !  x  f  x                               ",
   "               x           x         x!        !!!       !           !x !!!                                       ",
   "               x           x         x!        !!!       !           !x!!!!!!!!!!!!!!                             ",
   "        xxxxxxxx           xxxxx     x!        !!!       !           !xxxxxxxxxxxxx!!                             ",
   "                               x     x!        !!!       !           !             !!         xxxx                ",
   " xxx                           x     x!        !!!       !           !             !!                             ",
   "                               x     xv        !!!       !           v             !!                             ",
   "     o                         x     x         !!!       !                         !!                  o          ",
   "                               x     x         !!!       !                         !!                             ",
   "    xxx                        x     x         !!!       !                         !!                  o          ",
   "               !!!!!!!         xx   xx         !!!       !                         !!                 xxxx        ",
   "              xx     xx         x   x          !!!       !                         !!                             ",
   "             xx       xx        x o x          !!!       !                         !!                             ",
   "     @       x         x        x   x          !!!       !                         !!                             ",
   "    xxx      x         x        x   x          !!!       !                         !!                             ",
   " f  x x f  f x         x  f    xx o xx!!    f  !!!    f  !                         !!                             ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!!!!!!!!!!!!!!!!!!                   !!                             ",
   "!!!!x x!!!!!!x         x!!!!!xx       xx!!!!!!!!!!!!!!!!!!!!!xx!                   !!                             ",
   "!!!!x x!!!!!!x         x!!!!!x    o    x!!!!!!!!!!!!!!!!!!!!xx !                   !!                             ",
   "!!!!x x!!!!!!x         x!!!!!x         x!!!!!!!!!!!!!!!!!!!xx  !                   !!                             ",
   "!!!!x x!!!!!!x         x!!!!!xx       xx!!!!!!!!!!!!!!!!!!xx   !                   !!                             ",
   "!!!!x x!!!!!!x         x!!!!!!xxxpppxxx!!!!!!!!!!!!!!!!!!xx    !                   !!                             ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                   !!                             "],
  ["yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "          yy!!!!!!yy                  yy!!!!!yy                  yy!!!!!yy                yy!!!!!yy              ",
   "           yy!!!!yy                    yy!!!yy                    yy!!!yy                  yy!!!yy               ",
   "             !!!!                        !!!y   y                    v                        !                  ",
   "             !!!!                        !!!y   y                     v                       !                  ",
   "             !!!!                        !!!y   y                x        x    x     x        !                  ",
   "             !!!!                        !!!y   y              x                       x      !                  ",
   "             !!!!                        !!!y   y             x                          x    !                  ",
   "             !!!!                        !!!xx  y           x                             x   !                  ",
   "             !!!!                        !!! x  x          x                               x  !                  ",
   "             !!!!                        !!! x   x        x                                 x !                  ",
   "             !!!!                        !!! x    x      x                                   x!!                 ",
   "            !!!!!!                       !!! x     x    x                                     x!!                ",
   "           !!!!!!!!                      !!! x      x  x                                       x!                ",
   "           !xxxxxx!                  xyyx!!!xx       x                 o        o              x!                ",
   "           v      v                x     v v x                                                 x!                ",
   "                                 x        v  x                                                 x!                ",
   "                        xx      x            x                                                 x!                ",
   "                        x x    x                                  xx   f    x   f    xx        x!                ",
   "             o  o       x  x  x                      x             x!!!!!!!!!!!!!!!!!x         x!                ",
   "                        x   x                       x  x           x!!!!!!!!!!!!!!!!!x        x !                ",
   "             xxxx                            x     x    x          xxxxxxxxxxxxxxxxxxx       x  !                ",
   "                                             x    x      x                                  x   !                ",
   "                                             x   x        x                                x    v                ",
   "                                             x  x          x                              x                      ",
   "         xxx!!!!!!xxx   x   x                xxx             x                           x                       ",
   "   o       x!!!!!!x     x  x  x  o                        yyx x                         x                        ",
   "           xxxxxxxx     x x    x                         x                             x                         ",
   "  xxx                   xx      x                      x            x x x x x xyyyyx x                           ",
   "                                 x    o  xxx   o  o   x                   x                                      ",
   "                                   x     x  x        x                     x                                     ",
   "=                                    xppxx   x      x                       x                                    ",
   "        xxx          o                   x    x!!!!x                         x                                   ",
   "                                         x     x!!x                           x                                  ",
   "                   xxxxxx                x      xv                            x                   o              ",
   "                    x x x                x o                                                                     ",
   "                    x x x                x                                          o   o       xxxxx            ",
   "=                   x x xxx              x                  xxppppxx                                             ",
   "                  xxx x            o o   x                                         xxxxxxx                       ",
   "               xxxx!x x                  x o    x                             x    x!!!!!x                       ",
   "              =!!!!!x x            xxx   x     x  x                          x     x!!xx!x                       ",
   "               !!!!!x x f  f  xxxxxx!xxxxx    x  ! x                        x       !!  !                        ",
   "         @    !!!!!!x x!!!!!!!!!!!!!!!!!!x   x  !!!  x       o     o       x        !!  !      f           f     ",
   "   f  xxxxxxx!!!!!!!x x!!!!!!!!!!!!!!!!!!x  x  !!!!! x                    x   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!x x!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!x                  x  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! yxy yyxx yyxyy xx !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                               |            |            |        xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                               y                                                  x xxx       ",
   "                                                                                                  x x x       ",
   "                                           y                       o        o          o      o   xxx x       ",
   "                                               yy             x=      |           |                  =x       ",
   "                                               yy             xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "                                                              x   x x   x x   x x   x x   x x   x x           ",
   "                                        yyy                 xxxxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "                                        yyy                     x x   x x   x x   x x   x x   x x     x       ",
   "                                                              xxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                         xxxxxxxxx                                                            ",
   "                                         xyxyxyxyx      xx                                                    ",
   "                                         xyyyyyyyx                                                            ",
   "                                      o  x!!!!!!!x                                                            ",
   "               o                         x !!!!! x                                                            ",
   "                        xxxxxxx     xxxxxx  !!!  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               ",
   "             xx!xx      x                    v                                                x               ",
   "                        xxxxx    o                                                        xxxxx               ",
   "     o                      x                                                             x                   ",
   "                           =xyxxxyyxxxx                 xxx                xpx            x                   ",
   "   xx!xx                    x      x   x               x   x              x   x           x                   ",
   "                            x     x     x             x     x        o   x     x          x                   ",
   "              o             x     x     x             x     x            x     x          x                   ",
   " =                          x      x   x               x   x        xxx   x   x           x                   ",
   "            xx!xx           x       xxx                 xxx                xxx            x                   ",
   "     @                      x                                                             x                   ",
   "   pxxx                      x            x=    o         o     =x                       x                    ",
   "   x  x                       x           yyyxxxxxxxxxxyxxxxxxxxxx                      x                     ",
   "  !x  x!    !!!!!!     !!!!!!  x  !!!!!!     !!!!!!     !!!!!!     !!!!!!    !!!!!!    x!!!!!!     !!!!!!     ",
   " !!x  x!! f!!!!!!!! f !!!!!!!! fx!!!!!!!! f !!!!!!!! f !!!!!!!! f !!!!!!!!f !!!!!!!! f !!!!!!!! f !!!!!!!! f !",
   "!!!x  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!x  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!x  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
 ["yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
  "y!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!y",
  "y!!                                                                                                            !!y",
  "y!!                o                                                     o                                     !!y",
  "y!!                                                                                                            !!y",
  "y!!    o                                                                            o                          !!y",
  "y!!                                                                                                            !!y",
  "y!!                    xx       xx    xxxxxxxxxx    xxx      xxx                                               !!y",
  "y!!                    xx       xx   xxxx    xxxx   xxx      xxx                                               !!y",
  "y!!         o          xx       xx   xxx      xxx   xxx      xxx               o                               !!y",
  "y!!                    xx       xx   xx        xx   xxx      xxx                                o              !!y",
  "y!!                    xx       xx   xx        xx   xxx      xxx                                               !!y",
  "y!!                    xx       xx   xx        xx   xxx      xxx                                               !!y",
  "y!!                    xxx     xxx   xxx      xxx   xxx      xxx               o                               !!y",
  "y!!                    xxxxxxxxxxx   xxxx    xxxx    xxx    xxx                                                !!y",
  "y!!                             xx    xxxxxxxxxx      xxxxxxxx                                                 !!y",
  "y!!             o               xx                                                        o                    !!y",
  "y!!                             xx                                                                             !!y",
  "y!!                     xx      xx    xxx               xxx   xx   xx xxxxxxx                                  !!y",
  "y!!                     xx      xx    xxx               xxx   xx   xxxxxxxxxxxx                                !!y",
  "y!!                     xxx    xxx    xxx               xxx   xx   xxx       xx                                !!y",
  "y!!                     xxxxxxxxxx    xxx      xxx      xxx   xx   xx        xx                                !!y",
  "y!!                                   xxx      xxx      xxx   xx   xx        xx                                !!y",
  "y!!                                   xxx      xxx      xxx   xx   xx        xx                                !!y",
  "y!!                                   xxx      xxx      xxx   xx   xx        xx                                !!y",
  "y!!                                    xxx    xxxxx    xxx    xx   xx        xx                                !!y",
  "y!!                                     xxxxxxxx xxxxxxxx     xx   xx        xx                                !!y",
  "y!!                                                                                                            !!y",
  "y!!                                                                                                            !!y",
  "y!!                                                                                                            !!y",
  "y!!  @                                                                                                         !!y",
  "y!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!y",
  "y!!!x x!!!!!!x                                           f                                                     !!y",
  "y!!!x x!!!!!!x    f     x!!!!!xx    f   xxxxxxxxxxxxxx!!!!!!xx   !         f                    f              !!y",
  "y!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!y",
  "y!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!y",
  "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
